<?php
	$nonce = \Tracy\Helpers::getNonce();
	$nonceAttr = $nonce ? ' nonce="' . \Tracy\Helpers::escapeHtml($nonce) . '"' : '';
?><style type="text/css"<?php echo $nonceAttr; ?>><?php
	include_once(__DIR__ . '/routing.panel.css');
?></style>
<div class="tracy-panel-routing">
	<h1><?php echo $this->view->panelTitle; ?></h1>
	<?php if (!empty($this->view->requestedUrl)): ?>
		<p class="requested-url">
			<?php echo $this->view->requestedUrl->method; ?>
			<?php echo $this->view->requestedUrl->baseUrl; ?><span><?php echo $this->view->requestedUrl->path; ?></span>
		</p>
	<?php endif ?>
	<?php if (empty($this->view->items)): ?>
		<p>No routes defined.</p>
	<?php else: ?>
		<table class="routes-configuration">
			<thead>
				<tr>
					<th></th>
					<th>HTTP<br />Method</th>
					<th>Match<br />&nbsp;&nbsp;&nbsp;Reverse</th>
					<th>Route Name<br />&nbsp;&nbsp;&nbsp;Defaults</th>
					<th>Matched Controller:Action<br />&nbsp;&nbsp;&nbsp;Matched GET Params</th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->view->items as & $item): ?>
					<tr class="<?php
						echo ($item->matched == 1) ? 'matched-by-route' : (($item->matched == 2) ? 'matched-by-default' : '');
					?>">
						<td>
							<?php echo ($item->matched == 1) ? '✓' : (($item->matched == 2) ? '≈' : ''); ?>
						</td>
						<td><?php echo $item->method; ?></td>
						<td title="<?php echo $item->className; ?>">
							<span class="pattern"><?php
								echo $item->match;
							?></span><br />&nbsp;&nbsp;<span class="reverse"><?php
								echo $item->reverse;
							?></span>
						</td>
						<td>
							<?php if (isset($item->ctrlActionLink) && $item->ctrlActionLink[0]): ?>
								<a class="mvc-link" title="<?php
									echo $item->ctrlActionLink[1];
								?>" href="<?php echo $item->ctrlActionLink[0]; ?>"><b><?php
									echo $item->routeName;
								?></b></a>
							<?php else: ?>
								<b class="mvc-link" title="Unable to locate Controller/Action"><?php
									echo $item->routeName;
								?></b>
							<?php endif; ?>
							<span class="params">
								<?php foreach ($item->defaults as $key => $value): ?>
									<?php echo $key; ?>&nbsp;=&nbsp;<?php echo $value; ?>
								<?php endforeach; ?>
							</span>
						</td>
						<?php if ($item->matched): ?>
							<td>
								<?php if (is_array($item->ctrlActionLink) && $item->ctrlActionLink[0]): ?>
									<a class="mvc-link" title="<?php
										echo $item->ctrlActionLink[1];
									?>" href="<?php echo $item->ctrlActionLink[0]; ?>">
										<b><?php echo $item->ctrlActionName; ?></b>
									</a>
								<?php else: ?>
									<b class="mvc-link" title="Unable to locate Controller/Action"><?php echo $item->ctrlActionName; ?></b>
								<?php endif; ?>
								<span class="params">
									<?php foreach ($item->params as $key => $value): ?>
										<?php echo $key; ?>&nbsp;=&nbsp;<?php echo $value; ?>
									<?php endforeach; ?>
								</span>
							</td>
						<?php else: ?>
							<td></td>
						<?php endif; ?>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	<?php endif ?>
	<?php echo $this->_debugCode; ?>
</div>
